config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
  resources :questions, only: [:show]
  get "questions/:id/follow_user/:user_id", to: "questions#follow_user", as: "follow_user"
  get "questions/:id/follow_topic/:topic_id", to: "questions#follow_topic", as: "follow_topic"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  extend FriendlyId
  friendly_id :secure_slug, use: :slugged

  def secure_slug
  	@random_slug ||=persisted? ? friendly_id : "#{Time.now.to_i}-#{(0...10).map { ('a'..'z').to_a[rand(26)] }.join}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_many :answers

  extend FriendlyId
  friendly_id :secure_slug, use: :slugged

  def secure_slug
    @random_slug ||=persisted? ? friendly_id : "#{Time.now.to_i}-#{title.parameterize}"
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :questions

  extend FriendlyId
  friendly_id :secure_slug, use: :slugged

  acts_as_followable

  def secure_slug
    @random_slug ||=persisted? ? friendly_id : "#{Time.now.to_i}-#{name.parameterize}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers

  validates :name, presence: true

  extend FriendlyId
  friendly_id :secure_slug, use: :slugged

  acts_as_followable

  acts_as_follower

  def topics
    following_by_type('Topic')
  end

  def following
    following_by_type('User')
  end

  def secure_slug
    @random_slug ||=persisted? ? friendly_id : "#{Time.now.to_i}-#{name.parameterize}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
    @question = Question.includes(:topic, answers: [:user]).friendly.find(params[:id])
  end

  def follow_user
  	@question = Question.includes(:topic, answers: [:user]).friendly.find(params[:id])
  	user = User.friendly.find(params[:user_id])
  	if current_user.following?(user)
      redirect_to question_path(@question), flash: { alert: "Already following" }
  	else
  	  current_user.follow(user)
  	  redirect_to question_path(@question), flash: { notice: "You followed #{user.name}" }
  	end
  end

  def follow_topic
    @question = Question.includes(:topic, answers: [:user]).friendly.find(params[:id])
  	topic = Topic.friendly.find(params[:topic_id])
  	if current_user.following?(topic)
      redirect_to question_path(@question), flash: { alert: "Already following" }
  	else
  	  current_user.follow(topic)
  	  redirect_to question_path(@question), flash: { notice: "You followed #{topic.name}" }
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<ul>
  <% @questions.each do |question| -%>
    <li>
      <%= link_to question.title, question_path(question.slug), class: "question" %>
    </li>
  <% end -%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quora</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_url, method: :delete %>
    <% end %>

    <p>
      <%= flash[:notice] %>
      <%= flash[:alert] %>
    </p>

    <%= yield %>
  </body>
</html>

app/views/questions/show.html.erb
<div class="queston_header">
  <h1>
    <%= link_to @question.title, question_path(@question.slug), class: "question" %>
  </h1>
</div>
<div class="question_answers">
  <ul>
  	<% @question.answers.each do |answer| -%>
    <li class="answer">
      <%= answer.body %>
      <hr/>
      <span>
        <strong>Answered by:</strong> <%= answer.user.try(:name) %>
        <%= link_to "Follow User", follow_user_path(@question.slug, answer.user.slug), class: "follow_user" %>
      </span>
      <span>
        <strong>Topic: </strong> <%= @question.topic.try(:name) %>
        <%= link_to "Follow Topic", follow_topic_path(@question.slug, @question.topic.slug), class: "follow_topic" %>
      </span>
    </li>
    <% end -%>
  </ul>
</div>